version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@2.3.0

jobs:
  run_tests:
    parameters:
      redmine_version:
        type: string
        default: latest
      redmine_product:
        type: string
        default: redmine
      ruby_version:
        type: string
        default: latest
      database:
        type: enum
        enum:
          - mysql
          - pg
          - mariadb
          - sqlite3
        default: pg
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: << parameters.ruby_version >>
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
          product: << parameters.redmine_product >>
      - run:
          working_directory: redmine
          command: |
            touch Gemfile.local
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test
      - store_artifacts:
          path: redmine/tmp/screenshots
          destination: screenshots

workflows:
  version: 2
  test:
    jobs:
      - run_tests:
          name: latest Ruby, latest Redmine, PostgreSQL
      # Ruby versions
      #
      # About no ruby-3.1:
      # CircleCI doesn't create circleci/ruby:3.1-node-browsers .
      # So, we must implement https://github.com/agileware-jp/redmine-plugin-orb/pull/50
      - run_tests:
          name: ruby-3.0
          ruby_version: "3.0"
      - run_tests:
          name: ruby-2.7
          ruby_version: "2.7"
      - run_tests:
          name: ruby-2.6
          ruby_version: "2.6"
      # Redmine versions
      - run_tests:
          name: redmine-5.0
          redmine_version: "5.0.5"
      - run_tests:
          name: redmine-4.2
          redmine_version: "4.2.10"
          ruby_version: "2.7" # https://github.com/redmine/redmine/blob/4.2.10/Gemfile#L3
      - run_tests:
          name: redmine-4.1
          redmine_version: "4.1.7"
          ruby_version: "2.6" # https://github.com/redmine/redmine/blob/4.1.7/Gemfile#L3
      # Databases
      - run_tests:
          name: MySQL
          database: mysql
      - run_tests:
          name: MariaDB
          database: mariadb
      - run_tests:
          name: SQLite
          database: sqlite3
