version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@3.2.0

jobs:
  run_tests:
    parameters:
      redmine_version:
        type: string
        default: latest
      redmine_product:
        type: string
        default: redmine
      ruby_version:
        type: string
        default: "3.1" # https://github.com/redmine/redmine/blob/5.0.5/Gemfile#L3
      database:
        type: enum
        enum:
          - mysql
          - pg
          - mariadb
          - sqlite3
        default: pg
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: << parameters.ruby_version >>
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
          product: << parameters.redmine_product >>
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test
      - store_artifacts:
          path: redmine/tmp/screenshots
          destination: screenshots
      - run:
          name: Output versions
          when: always
          working_directory: redmine
          command: |
            set -eux -o pipefail
            lsb_release --all
            google-chrome --version
            chromedriver --version
            ruby --version
            bin/rails runner --environment=test 'p(Redmine::VERSION::ARRAY)'
            gem --version
            bundle --version
      - run:
          name: Output gem versions
          when: always
          working_directory: redmine
          command: bundle list
      - run:
          name: Output deb package versions
          when: always
          command: dpkg -l

workflows:
  version: 2
  test:
    jobs:
      - run_tests:
          name: latest Ruby, latest Redmine, PostgreSQL
      - run_tests:
          name: ruby-3.1
          ruby_version: "3.1"
      - run_tests:
          name: ruby-3.0
          ruby_version: "3.0"
      - run_tests:
          name: ruby-2.7
          ruby_version: "2.7"
      - run_tests:
          name: ruby-2.6
          ruby_version: "2.6"
      # Redmine versions
      - run_tests:
          name: redmine-5.0
          redmine_version: "5.0"
          ruby_version: "3.1" # https://github.com/redmine/redmine/blob/5.0.5/Gemfile#L3
      - run_tests:
          name: redmine-4.2
          redmine_version: "4.2"
          ruby_version: "2.7" # https://github.com/redmine/redmine/blob/4.2.10/Gemfile#L3
      - run_tests:
          name: redmine-4.1
          redmine_version: "4.1"
          ruby_version: "2.6" # https://github.com/redmine/redmine/blob/4.1.7/Gemfile#L3
      # Databases
      - run_tests:
          name: MySQL
          database: mysql
      - run_tests:
          name: MariaDB
          database: mariadb
      - run_tests:
          name: SQLite
          database: sqlite3
